name: Foo-Bar Github Actions Test
on: [pull_request, push]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Docker
        uses: docker/setup-qemu-action@v2
      
      - name: Install Kind
      #I am using a macbook locally hence the usage of 'brew'
        run: |
          brew install kind  


      - name: Creating the Cluster
        run: |
          KIND_CLUSTER_NAME=foo-bar-cluster

          if [ "$(kind get clusters | grep $KIND_CLUSTER_NAME)" == "$KIND_CLUSTER_NAME" ]; then
            echo "Cluster already exists."
          else
            echo "Creating cluster..."
              kind create cluster --name $KIND_CLUSTER_NAME --config ./k8s/config/myCluster.yaml
          fi

   
      - name:  INGRESS-CONTROLLER INSTALLATION
        run: |

          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          
          kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=90s

      - name: INSTALLING METALLB
        run: |
            kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
            kubectl wait --namespace metallb-system  --for=condition=ready pod --selector=app=metallb --timeout=90s

      - name: DEPLOYING FOO 
        run: kubectl apply -f ./k8s/lb-foo.yaml 

      - name: DEPLOYING BAR
        run: | 
            kubectl apply -f ./k8s/lb-bar.yaml 
           

      - name: FOO & BAR INGRESS
        run: |
            docker network inspect  
            kubectl apply -f ./k8s/ingress.yaml

      - name: TEST FOO BAR
        run: |
            for _ in {1..10}; do curl foo.localhost; done            
            for _ in {1..10}; do curl bar.localhost; done
          
